// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RiosFinalSchool.Models
{
    public partial class Assignment
    {
        public int AssignId { get; set; }
        public int CourseId { get; set; }
        public string AssignName { get; set; }
        public int StudentId { get; set; }
        public int AssignPoints { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}