// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RiosFinalSchool.Models
{
    public partial class Course
    {
        public int CourseId { get; set; }
        public int InstructorId { get; set; }
        public string CourseName { get; set; }
        public string CourseSubject { get; set; }
        public double CoursePrice { get; set; }

        public virtual Instructor Instructor { get; set; }
        public virtual Assignment Assignment { get; set; }
    }
}