// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RiosFinalSchool.Models
{
    public partial class Instructor
    {
        public int InstructorId { get; set; }
        public string InstructorFname { get; set; }
        public string InstructorLname { get; set; }
        public string InstructorEmail { get; set; }
        public int InstructorStatus { get; set; }

        public virtual Course Course { get; set; }
    }
}