// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RiosFinalSchool.Models
{
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudentFname { get; set; }
        public string StudentLname { get; set; }
        public string StudentEmail { get; set; }
        public string StudentZipcode { get; set; }

        public virtual Assignment Assignment { get; set; }
    }
}